"""adiciona knowledge_reviews

Revision ID: 1c8a4cf1df49
Revises: c7c3d6192fe5
Create Date: 2026-07-21 12:55:56.628278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8a4cf1df49'
down_revision: Union[str, Sequence[str], None] = 'c7c3d6192fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_node_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('old_interval', sa.Integer(), nullable=False),
    sa.Column('new_interval', sa.Integer(), nullable=False),
    sa.Column('old_factor', sa.Float(), nullable=False),
    sa.Column('new_factor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_reviews_knowledge_node_id'), 'knowledge_reviews', ['knowledge_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_reviews_knowledge_node_id'), table_name='knowledge_reviews')
    op.drop_table('knowledge_reviews')
    # ### end Alembic commands ###
