"""Flashcards

Revision ID: 2b9b0f6bad84
Revises: 36fab1a2fb7e
Create Date: 2026-08-20 11:09:45.627608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b9b0f6bad84'
down_revision: Union[str, Sequence[str], None] = '36fab1a2fb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    op.create_index('ix_decks_user_id_is_main_unique', 'decks', ['user_id'], unique=True, postgresql_where=sa.text('is_main = true'))
    op.create_table('user_push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_push_tokens_push_token'), 'user_push_tokens', ['push_token'], unique=True)
    op.create_index(op.f('ix_user_push_tokens_user_id'), 'user_push_tokens', ['user_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_node_id', sa.Integer(), nullable=True),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fsrs_state', sa.String(length=15), nullable=False),
    sa.Column('fsrs_step', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_easy_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_flashcards_knowledge_node_id'), 'flashcards', ['knowledge_node_id'], unique=False)
    op.create_index(op.f('ix_flashcards_status'), 'flashcards', ['status'], unique=False)
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('old_stability', sa.Float(), nullable=True),
    sa.Column('new_stability', sa.Float(), nullable=True),
    sa.Column('old_difficulty', sa.Float(), nullable=True),
    sa.Column('new_difficulty', sa.Float(), nullable=True),
    sa.Column('elapsed_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_reviews_flashcard_id'), 'flashcard_reviews', ['flashcard_id'], unique=False)
    op.drop_index('ix_knowledge_reviews_knowledge_node_id', table_name='knowledge_reviews')
    op.drop_table('knowledge_reviews')
    op.add_column('knowledge_nodes', sa.Column('mission_id', sa.Integer(), nullable=True))
    op.add_column('knowledge_nodes', sa.Column('importance_score', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_knowledge_nodes_mission_id'), 'knowledge_nodes', ['mission_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_nodes', 'missions', ['mission_id'], ['id'])
    op.drop_column('knowledge_nodes', 'last_review_at')
    op.drop_column('knowledge_nodes', 'repetition_count')
    op.drop_column('knowledge_nodes', 'easiness_factor')
    op.drop_column('knowledge_nodes', 'next_review_date')
    op.drop_column('knowledge_nodes', 'interval_days')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('knowledge_nodes', sa.Column('interval_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('knowledge_nodes', sa.Column('next_review_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('knowledge_nodes', sa.Column('easiness_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('knowledge_nodes', sa.Column('repetition_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('knowledge_nodes', sa.Column('last_review_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'knowledge_nodes', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_nodes_mission_id'), table_name='knowledge_nodes')
    op.drop_column('knowledge_nodes', 'importance_score')
    op.drop_column('knowledge_nodes', 'mission_id')
    op.create_table('knowledge_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('knowledge_node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('old_interval', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_interval', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('new_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], name='knowledge_reviews_knowledge_node_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='knowledge_reviews_pkey')
    )
    op.create_index('ix_knowledge_reviews_knowledge_node_id', 'knowledge_reviews', ['knowledge_node_id'], unique=False)
    op.drop_index(op.f('ix_flashcard_reviews_flashcard_id'), table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_status'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_knowledge_node_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_user_push_tokens_user_id'), table_name='user_push_tokens')
    op.drop_index(op.f('ix_user_push_tokens_push_token'), table_name='user_push_tokens')
    op.drop_table('user_push_tokens')
    op.drop_index('ix_decks_user_id_is_main_unique', table_name='decks', postgresql_where=sa.text('is_main = true'))
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_table('decks')
    # ### end Alembic commands ###
