"""notifications

Revision ID: 36fab1a2fb7e
Revises: e86078c60808
Create Date: 2026-08-15 23:27:41.369965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fab1a2fb7e'
down_revision: Union[str, Sequence[str], None] = 'e86078c60808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_push_tokens_push_token'), 'user_push_tokens', ['push_token'], unique=True)
    op.create_index(op.f('ix_user_push_tokens_user_id'), 'user_push_tokens', ['user_id'], unique=False)
    op.add_column('calendar_events', sa.Column('reminder_dispatched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reminders', sa.Column('last_dispatched_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'last_dispatched_date')
    op.drop_column('calendar_events', 'reminder_dispatched_at')
    op.drop_index(op.f('ix_user_push_tokens_user_id'), table_name='user_push_tokens')
    op.drop_index(op.f('ix_user_push_tokens_push_token'), table_name='user_push_tokens')
    op.drop_table('user_push_tokens')
    # ### end Alembic commands ###
