"""adiciona ritmo, conhecimento previo e estimativa ao goal

Revision ID: 469ac234095c
Revises: 98cb3f549b7d
Create Date: 2026-07-13 22:26:23.211053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469ac234095c'
down_revision: Union[str, Sequence[str], None] = '98cb3f549b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('weekly_active_days', sa.Integer(), nullable=True))
    op.add_column('goals', sa.Column('daily_time_minutes', sa.Integer(), nullable=True))
    op.add_column('goals', sa.Column('prior_knowledge_level', sa.String(length=20), nullable=True))
    op.add_column('goals', sa.Column('estimated_completion_weeks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'estimated_completion_weeks')
    op.drop_column('goals', 'prior_knowledge_level')
    op.drop_column('goals', 'daily_time_minutes')
    op.drop_column('goals', 'weekly_active_days')
    # ### end Alembic commands ###
