"""adiciona username ao user

Revision ID: 486518d8de3c
Revises: 2f9c36d84511
Create Date: 2026-07-19 13:41:52.112552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486518d8de3c'
down_revision: Union[str, Sequence[str], None] = '2f9c36d84511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # AFTER
    op.add_column('roadmap_chapters', sa.Column('closed_early', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('roadmap_chapters', 'closed_early')
    # ### end Alembic commands ###
