"""user status

Revision ID: 874c7c74152d
Revises: 0a93d7dc8a87
Create Date: 2026-08-21 03:48:01.603496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874c7c74152d'
down_revision: Union[str, Sequence[str], None] = '0a93d7dc8a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('last_bonus_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'last_bonus_date')
    # ### end Alembic commands ###
