"""adiciona status de geracao e torna title opcional

Revision ID: 98cb3f549b7d
Revises: 9e357001bf84
Create Date: 2026-07-12 21:09:08.220860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cb3f549b7d'
down_revision: Union[str, Sequence[str], None] = '9e357001bf84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
