"""adiciona status de geracao ao goal

Revision ID: 9e357001bf84
Revises: 41d88e1cd85c
Create Date: 2026-07-12 20:42:02.307609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e357001bf84'
down_revision: Union[str, Sequence[str], None] = '41d88e1cd85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('generation_status', sa.String(length=20), nullable=False))
    op.add_column('goals', sa.Column('generation_error', sa.Text(), nullable=True))
    op.alter_column('goals', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('goals', 'generation_error')
    op.drop_column('goals', 'generation_status')
    # ### end Alembic commands ###
