"""adiciona involves_learning, closed_early e knowledge_nodes

Revision ID: c7c3d6192fe5
Revises: fbe2d6040981
Create Date: 2026-07-20 20:57:49.776119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c3d6192fe5'
down_revision: Union[str, Sequence[str], None] = 'fbe2d6040981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_goal_id'), 'knowledge_nodes', ['goal_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_user_id'), 'knowledge_nodes', ['user_id'], unique=False)
    op.add_column('goals', sa.Column('involves_learning', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'involves_learning')
    op.drop_index(op.f('ix_knowledge_nodes_user_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_goal_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
