"""add email_verified to users

Revision ID: eba295ddb888
Revises: 7e5dfea2e2c3
Create Date: 2026-08-18 09:56:07.297563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eba295ddb888'
down_revision: Union[str, Sequence[str], None] = '7e5dfea2e2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_push_tokens_push_token', table_name='user_push_tokens')
    op.drop_index('ix_user_push_tokens_user_id', table_name='user_push_tokens')
    op.drop_table('user_push_tokens')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.create_table('user_push_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('push_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_push_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_push_tokens_pkey')
    )
    op.create_index('ix_user_push_tokens_user_id', 'user_push_tokens', ['user_id'], unique=False)
    op.create_index('ix_user_push_tokens_push_token', 'user_push_tokens', ['push_token'], unique=True)
    # ### end Alembic commands ###
